CREATE TABLE SIGNUP (
    USERID VARCHAR2(30) PRIMARY KEY,
    PASSWORD VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(10) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    PHONE VARCHAR2(30) NOT NULL,
    ADDR VARCHAR2(50) NOT NULL
);
​
CREATE TABLE CATEGORY (
    C_NUM NUMBER(6) PRIMARY KEY,
    C_NAME VARCHAR2(30) NOT NULL,
    C_SUB VARCHAR2(30) NOT NULL
);
​
CREATE TABLE P_BOARD (
    P_IDX NUMBER(6) PRIMARY KEY,
    C_NUM NUMBER(6) NOT NULL,
    CONSTRAINT P_BOARD_CATEGORY_FK FOREIGN KEY(C_NUM) REFERENCES CATEGORY(C_NUM),
    P_NAME VARCHAR2(50) NOT NULL,
    P_PRICE NUMBER(10) NOT NULL,
    P_CONTENT VARCHAR2(1000) NOT NULL,
    P_DISCOUNT NUMBER(3),
    P_TAG VARCHAR2(100),
    USERID VARCHAR2(30) NOT NULL,
    CONSTRAINT P_BOARD_ID_FK FOREIGN KEY(USERID) REFERENCES SIGNUP(USERID),
    P_DATE DATE NOT NULL,
    P_IMAGE VARCHAR2(100) NOT NULL,
    P_THUMBNAIL VARCHAR2(100) NOT NULL
)
;
​
CREATE TABLE P_REVIEW (
    P_IDX NUMBER(6) NOT NULL,
    CONSTRAINT P_REVIEW_IDX_FK FOREIGN KEY(P_IDX) REFERENCES P_BOARD(P_IDX),
    USERID VARCHAR2(30) NOT NULL,
    CONSTRAINT P_REVIEW_USERID_FK FOREIGN KEY(USERID) REFERENCES SIGNUP(USERID),
    R_SIZE VARCHAR2(10),
    R_COLORSIMILIARITY VARCHAR2(30) NOT NULL,
    R_SATISFACTION VARCHAR2(30) NOT NULL,
    R_CONTENT VARCHAR2(300) NOT NULL,
    R_DATE DATE DEFAULT SYSDATE,
    R_IDX NUMBER(6) PRIMARY KEY
)
;
​
CREATE TABLE P_INQUIRY (
    P_IDX NUMBER(6) NOT NULL,
    CONSTRAINT P_INQUIRY_IDX_FK FOREIGN KEY(P_IDX) REFERENCES P_BOARD(P_IDX),
    USERID VARCHAR2(30) NOT NULL,
    CONSTRAINT P_INQUIRY_USERID_FK FOREIGN KEY(USERID) REFERENCES SIGNUP(USERID),
    I_CATEGORY VARCHAR2(30) NOT NULL,
    I_CONTENT VARCHAR2(400) NOT NULL,
    I_ANSWER VARCHAR2(400),
    I_DATE DATE DEFAULT SYSDATE NOT NULL,
    I_IDX NUMBER(6) PRIMARY KEY
    )
;
​
CREATE TABLE P_OPTION (
    P_IDX NUMBER(6) NOT NULL,
    CONSTRAINT P_OPTION_IDX_FK FOREIGN KEY(P_IDX) REFERENCES P_BOARD(P_IDX),
    O_NAME VARCHAR2(200) NOT NULL,
    O_PRICE VARCHAR2(20) NOT NULL,
    O_SIZE VARCHAR2(20) NOT NULL
    )
;
​
CREATE TABLE O_CARTLIST (
    USERID VARCHAR2(30) NOT NULL,
    CONSTRAINT O_CARTLIST_USERID_FK FOREIGN KEY(USERID) REFERENCES SIGNUP(USERID),
    P_IDX NUMBER(6) NOT NULL,
    CONSTRAINT O_CARTLIST_P_IDX_FK FOREIGN KEY(P_IDX) REFERENCES P_BOARD(P_IDX)
    )
;
​
CREATE TABLE SELLER_REGIST (
    SR_IDX VARCHAR2(20) PRIMARY KEY,
    SR_RNAME VARCHAR2(20) NOT NULL,
    SR_SHOPNAME VARCHAR2(100) NOT NULL,
    SR_NUMBER VARCHAR2(20) NOT NULL,
    SR_ADDRESS VARCHAR2(100) NOT NULL,
    SR_NAME VARCHAR2(20) NOT NULL,
    SR_EMAIL VARCHAR2(50) NOT NULL,
    SR_PHONE VARCHAR2(20) NOT NULL,
    SR_CHECK VARCHAR2(20) NOT NULL
)
;
​
CREATE TABLE SHOP (
    S_IDX NUMBER(6) PRIMARY KEY,
    USERID VARCHAR2(30) NOT NULL,
    CONSTRAINT SHOP_USERID_FK FOREIGN KEY(USERID) REFERENCES SIGNUP(USERID), 
    SR_IDX VARCHAR2(20) NOT NULL,
    CONSTRAINT SHOP_SR_IDX_FK FOREIGN KEY(SR_IDX) REFERENCES SELLER_REGIST(SR_IDX),
    S_IMAGE VARCHAR2(20) NOT NULL,
    S_SATIS VARCHAR2(50) NOT NULL
)
;
​
ALTER TABLE P_BOARD
ADD CONSTRAINTS P_BOARD_S_IDX_PK FOREIGN KEY(S_IDX)
REFERENCES SHOP(S_IDX);
​
CREATE TABLE O_ORDER(
    O_NUM NUMBER(12) PRIMARY KEY,
    USERID VARCHAR2(30) NOT NULL,
    CONSTRAINT O_ORDER_SIGNUP_FK FOREIGN KEY(USERID) REFERENCES SIGNUP(USERID),
    S_IDX NUMBER(6) NOT NULL,
    CONSTRAINT O_ORDER_S_IDX_FK FOREIGN KEY(S_IDX) REFERENCES SHOP(S_IDX),
    P_IDX NUMBER(6) NOT NULL,
    CONSTRAINT O_ORDER_P_IDX_FK FOREIGN KEY(P_IDX) REFERENCES P_BOARD(P_IDX),
    O_PRODUCT VARCHAR2(50) NOT NULL,
    O_PLACE VARCHAR2(80) NOT NULL,
    O_ORDER VARCHAR2(150),
    O_ACCOUNT VARCHAR2(30) NOT NULL,
    O_PAY VARCHAR2(30) NOT NULL,
    O_DATE DATE NOT NULL,
    O_CON VARCHAR2(30) NOT NULL
    )
;
​
CREATE TABLE O_ARRIVE (
    USERID VARCHAR2(30) NOT NULL,
    CONSTRAINT O_ARRIVE_USERID_FK FOREIGN KEY(USERID) REFERENCES SIGNUP(USERID),
    A_PERSON VARCHAR2(150) NOT NULL,
    A_ADDRESS VARCHAR2(50) NOT NULL,
    A_DETAIL VARCHAR2(30) NOT NULL,
    A_ZIP VARCHAR2(20)
    )
;

CREATE SEQUENCE O_ORDER_SEQ NOCACHE;
CREATE SEQUENCE O_ARRIVE_SEQ NOCACHE;

COMMIT;

-------------------------------------------------------

INSERT INTO O_ORDER
VALUES (O_ORDER_SEQ.NEXTVAL, 'podongEbi', '1', '128', '어흥빤스', '남양주', 
        'gyungbisil', '110-319-569820', '카드', SYSDATE, '배송준비중');
        
INSERT INTO SIGNUP
VALUES ('podongEbi', '1208', '이민형', 'podong2@bit.com', '010-7187-7995', '덕소');

INSERT INTO SHOP
VALUES ('1', 'podongEbi', '(주)충진사마', 'img', '최상');

INSERT INTO P_BOARD
VALUES (128, 92, '어흥팬티', 59000, '최고급원단과최상의착용감', 1, 
        'X', 'podongEbi', sysdate, 'tiger_detail5.jpg', 'tiger.jpg');
        
INSERT INTO CATEGORY
VALUES ('92', '의류', '언더웨어');

INSERT INTO SELLER_REGIST
VALUES ('(주)충진사마', '이충진', '은영9', '02-111-1111', '서울 논현', '이충진', 'lee@test.com', '010-1111-1111', 'N');

INSERT INTO P_OPTION VALUES(128, '어흥빤스', '110');